---
title: "Affordances Behavioral Econ Analysis following Sanabria (in prep)"
author: "Carter Daniels"
date: "1/1/2024"
output: html_document
---

```{r, include=FALSE}
rm(list=ls())
#import libraries
library(tidyverse)
library(lme4)
library(stats)
library(shinystan)
library(cmdstanr)
library(posterior)
library(bayesplot)
library(ggridges)
library(patchwork)
library(ggtext)
library(ggprism)

```


```{r, include=FALSE}

#datapath and functions

data.path <- "D:\\Dropbox Drive Folder\\Dropbox\\2 All of Carter's Stuff\\Carter Local\\BHA_Econ_Sanabria\\"


Sanabria_BHEcon <- function(t,u,w,s,PR,RM) 
{

  Pn <- u*((u*RM)/(t+PR/w))^(s/(1-s))
  Bn <- PR/((t+PR/w)*(1+1/Pn))
  return(Bn)

}
```

```{r, include=FALSE}

tbt_matrices <- read.csv(paste0(data.path,"AH_LongForm_Carter.csv"))


#recode subjects
tbt_matrices$reCode_Subject <- 1
i=0
for (subj in unique(tbt_matrices$Rat))
{
  i = i + 1
  tbt_matrices$reCode_Subject[tbt_matrices$Rat==subj]<-i
}

tbt_matrices$LeverRecode <- tbt_matrices$LeverHeight - min(tbt_matrices$LeverHeight)

tbt_matrices$RewMag <- 1

tbt_matrices$CatLH <- 0
tbt_matrices$CatLH[tbt_matrices$LeverHeight==11]<-1
tbt_matrices$CatLH[tbt_matrices$LeverHeight==18]<-2

#tbt_matrices <- tbt_matrices[tbt_matrices$LeverRecode==10,]

OverSessions <- tbt_matrices %>% group_by(reCode_Subject,LeverRecode,PR,RewMag) %>% 
  summarise(across(.cols=c(Local.Rate),.fns=c(mean,sd)))
OverSessions$Local.Rate_3 <- OverSessions$Local.Rate_2 / OverSessions$Local.Rate_1

```


# Individual Data (scatter plots)


```{r, fig.width = 24, fig.height = 24, echo=FALSE, results='hide', message=FALSE, warning=FALSE}

ggplot() + 
  geom_point(data=tbt_matrices, aes(x=PR,y=Local.Rate,color=as.factor(LeverRecode)),size=2) + 
  geom_line(data=OverSessions,aes(x=PR,y=Local.Rate_1,color=as.factor(LeverRecode)),size=3) +
  ylab("Local Rate") + 
  xlab("Progressive Ratio")+
  facet_wrap(~reCode_Subject)

ggplot() + 
  geom_line(data=OverSessions,aes(x=PR,y=Local.Rate_2,color=as.factor(LeverRecode)),size=3) +
  ylab("Standard Deviation") + 
  xlab("Progressive Ratio") + 
  facet_wrap(~reCode_Subject)

ggplot() + 
  geom_line(data=OverSessions,aes(x=PR,y=Local.Rate_3,color=as.factor(LeverRecode)),size=3) +
  ylab("Coefficient of Variation") + 
  xlab("Progressive Ratio") + 
  facet_wrap(~reCode_Subject)

```



```{r, include=FALSE}

sanabria_econ <- "

// stan code for sanabria behavioral econ

data {

 int<lower=1> Nr; // number of data points
 int<lower=1> Ns; // number of subjects
 vector<lower=0>[Nr] y; //Local Rate stream
 int s[Nr]; //subject stream
 vector<lower=0>[Nr] Pr_req; //Programemd PR stream
 vector<lower=0>[Nr] LHStream; //Lever height stream
 vector<lower=1>[Nr] RewMagStream; //Reward Magnitude Stream
}

parameters {

//intercept
real t_int; 
real w_int;
real u_int; 
real H_int; 

//lever height effect
real t_beta_11;
real w_beta_11;
real u_beta_11; 
real H_beta_11; 

real t_beta_18;
real w_beta_18;
real u_beta_18; 
real H_beta_18; 

//intercept_rme;
vector[Ns] t_int_rme; 
vector[Ns] w_int_rme;
vector[Ns] u_int_rme;
vector[Ns] H_int_rme; 

//lever height rme;
vector[Ns] t_beta_11_rme;
vector[Ns] w_beta_11_rme;
vector[Ns] u_beta_11_rme;
vector[Ns] H_beta_11_rme; 

vector[Ns] t_beta_18_rme;
vector[Ns] w_beta_18_rme;
vector[Ns] u_beta_18_rme;
vector[Ns] H_beta_18_rme;

vector<lower=0>[Ns] sigma; 
//real<lower=0> sigma; 

}

transformed parameters {

vector<lower=0>[Nr] row_Bn; 
vector<lower=0>[Nr] row_Pn; 
vector<lower=0>[Nr] row_sigma; 
vector<lower=0>[Nr] t;
vector<lower=0>[Nr] w;
vector<lower=0>[Nr] u;
vector<lower=0>[Nr] H; 
vector<lower=0,upper=1>[Nr] row_s; 

for (si in 1:Nr)
{
  if (LHStream[si] == 0)
  {
    t[si] = exp((t_int + t_int_rme[s[si]]));
    w[si] = exp((w_int + w_int_rme[s[si]]));
    u[si] = exp((u_int + u_int_rme[s[si]]));
    H[si] = exp((H_int + H_int_rme[s[si]]));
  }
  else if (LHStream[si] == 1)
  {
    t[si] = exp((t_int + t_int_rme[s[si]])+((t_beta_11 + t_beta_11_rme[s[si]])*1));
    w[si] = exp((w_int + w_int_rme[s[si]])+((w_beta_11 + w_beta_11_rme[s[si]])*1));
    u[si] = exp((u_int + u_int_rme[s[si]])+((u_beta_11 + u_beta_11_rme[s[si]])*1));
    H[si] = exp((H_int + H_int_rme[s[si]])+((H_beta_11 + H_beta_11_rme[s[si]])*1));
  }
  else if (LHStream[si] == 2)
  {
    t[si] = exp((t_int + t_int_rme[s[si]])+((t_beta_18 + t_beta_18_rme[s[si]])*1));
    w[si] = exp((w_int + w_int_rme[s[si]])+((w_beta_18 + w_beta_18_rme[s[si]])*1));
    u[si] = exp((u_int + u_int_rme[s[si]])+((u_beta_18 + u_beta_18_rme[s[si]])*1));
    H[si] = exp((H_int + H_int_rme[s[si]])+((H_beta_18 + H_beta_18_rme[s[si]])*1));
  }

  row_s[si] = H[si]/(1+H[si]);
  row_sigma[si] = sigma[s[si]];

  row_Pn[si] = u[si]*pow(((u[si]*RewMagStream[si])/(t[si]+Pr_req[si]/w[si])),row_s[si]/(1-row_s[si]));
  row_Bn[si] = Pr_req[si]/((t[si]+Pr_req[si]/w[si])*(1+(1/row_Pn[si])));
  

}



}

model {

//intercept priors
t_int ~ normal(0,3);
w_int ~ normal(0,3);
u_int ~ normal(0,3); 
H_int ~ normal(0,3); //approximately flat on s 
sigma ~ normal(0,1) T[0,]; //Gelman recommends 

//beta priors
t_beta_11 ~ normal(0,2);
w_beta_11 ~ normal(0,2);
u_beta_11 ~ normal(0,2); 
H_beta_11 ~ normal(0,2);

t_beta_18 ~ normal(0,2);
w_beta_18 ~ normal(0,2);
u_beta_18 ~ normal(0,2); 
H_beta_18 ~ normal(0,2);

//rme priors
t_int_rme ~ normal(0,1);
w_int_rme ~ normal(0,1);
u_int_rme ~ normal(0,1); 
H_int_rme ~ normal(0,1);

t_beta_11_rme ~ normal(0,1);
w_beta_11_rme ~ normal(0,1);
u_beta_11_rme ~ normal(0,1); 
H_beta_11_rme ~ normal(0,1);

t_beta_18_rme ~ normal(0,1);
w_beta_18_rme ~ normal(0,1);
u_beta_18_rme ~ normal(0,1); 
H_beta_18_rme ~ normal(0,1);

//likelihood
y ~ normal(row_Bn,row_sigma) T[0,]; 
//y ~ lognormal(row_Bn,row_sigma); 

}


"

write_stan_file(sanabria_econ,
                dir=data.path,
                basename="sanabria_econ_Angeldata.stan",
                force_overwrite = TRUE)

#compile model
mod <- cmdstan_model(stan_file=file.path(paste0(data.path,
                                                "sanabria_econ_Angeldata.stan")))

##got divergent transitions
##trying half-normal on sigma


```

```{r, include=FALSE}
#construct predictor matrix


data_list <- list(Nr = nrow(tbt_matrices),
                  Ns = length(unique(tbt_matrices$reCode_Subject)),
                  y=tbt_matrices$Local.Rate,
                  s=tbt_matrices$reCode_Subject, 
                  Pr_req = tbt_matrices$PR,
                  LHStream = tbt_matrices$CatLH, 
                  RewMagStream = tbt_matrices$RewMag)




```


```{r, include=FALSE}

## mcmc

fit <- mod$sample(data=data_list,
                  seed=123,
                  chains=4,
                  parallel_chains = 4,
                  refresh=100,
                  num_samples=10000,
                  num_warmup=10000,
                  adapt_delta=0.99,
                  max_treedepth=30,
                  output_dir="D:/Dropbox Drive Folder/Dropbox/2 All of Carter's Stuff/Carter Local/BHA_Econ_Sanabria/AngelBayesOutput")
a <- fit$summary()

# fit <- mod$optimize(data=data_list)
# a <- fit$summary()
# colnames(a)<-c("variable","mean")

# fit <- mod$variational(data=data_list)

# a <- fit$summary()



```


```{r}

tbt_matrices_wpredictions <- tbt_matrices
fixed_effects <- a[c(2:9),]
rmes <- a[c(10:73),]

tbt_matrices_wpredictions$t <- fixed_effects$mean[1]
tbt_matrices_wpredictions$w <- fixed_effects$mean[2]
tbt_matrices_wpredictions$u <- fixed_effects$mean[3]
tbt_matrices_wpredictions$H <- fixed_effects$mean[4]
tbt_matrices_wpredictions$t_beta <- fixed_effects$mean[5]*tbt_matrices_wpredictions$LeverRecode
tbt_matrices_wpredictions$w_beta <- fixed_effects$mean[6]*tbt_matrices_wpredictions$LeverRecode
tbt_matrices_wpredictions$u_beta <- fixed_effects$mean[7]*tbt_matrices_wpredictions$LeverRecode
tbt_matrices_wpredictions$H_beta <- fixed_effects$mean[8]*tbt_matrices_wpredictions$LeverRecode

tbt_matrices_wpredictions$t_int_rme <- 0
tbt_matrices_wpredictions$w_int_rme <- 0
tbt_matrices_wpredictions$u_int_rme <- 0
tbt_matrices_wpredictions$H_int_rme <- 0

tbt_matrices_wpredictions$t_beta_rme <- 0
tbt_matrices_wpredictions$w_beta_rme <- 0
tbt_matrices_wpredictions$u_beta_rme <- 0
tbt_matrices_wpredictions$H_beta_rme <- 0

# for (ea_subj in unique(tbt_matrices_wpredictions$reCode_Subject))
# {
#   tbt_matrices_wpredictions$t_int_rme[tbt_matrices_wpredictions$reCode_Subject==ea_subj] <- rmes$mean[which(grepl(as.character(ea_subj),rmes$variable) & 
#                                                            grepl("t_int_rme",rmes$variable))]
#   tbt_matrices_wpredictions$w_int_rme[tbt_matrices_wpredictions$reCode_Subject==ea_subj] <- rmes$mean[which(grepl(as.character(ea_subj),rmes$variable) & 
#                                                            grepl("w_int_rme",rmes$variable))]
#   tbt_matrices_wpredictions$u_int_rme[tbt_matrices_wpredictions$reCode_Subject==ea_subj] <- rmes$mean[which(grepl(as.character(ea_subj),rmes$variable) & 
#                                                            grepl("u_int_rme",rmes$variable))]
#   tbt_matrices_wpredictions$H_int_rme[tbt_matrices_wpredictions$reCode_Subject==ea_subj] <- rmes$mean[which(grepl(as.character(ea_subj),rmes$variable) & 
#                                                            grepl("H_int_rme",rmes$variable))]
#   
#   tbt_matrices_wpredictions$t_beta_rme[tbt_matrices_wpredictions$reCode_Subject==ea_subj] <- rmes$mean[which(grepl(as.character(ea_subj),rmes$variable) & 
#                                                            grepl("t_beta_rme",rmes$variable))]
#   tbt_matrices_wpredictions$w_beta_rme[tbt_matrices_wpredictions$reCode_Subject==ea_subj] <- rmes$mean[which(grepl(as.character(ea_subj),rmes$variable) & 
#                                                            grepl("w_beta_rme",rmes$variable))]
#   tbt_matrices_wpredictions$u_beta_rme[tbt_matrices_wpredictions$reCode_Subject==ea_subj] <- rmes$mean[which(grepl(as.character(ea_subj),rmes$variable) & 
#                                                            grepl("u_beta_rme",rmes$variable))]
#   tbt_matrices_wpredictions$H_beta_rme[tbt_matrices_wpredictions$reCode_Subject==ea_subj] <- rmes$mean[which(grepl(as.character(ea_subj),rmes$variable) & 
#                                                            grepl("H_beta_rme",rmes$variable))]
# }

tbt_matrices_wpredictions$t_final <- (tbt_matrices_wpredictions$t +  tbt_matrices_wpredictions$t_int_rme) +
  (tbt_matrices_wpredictions$t_beta + tbt_matrices_wpredictions$t_beta_rme)

tbt_matrices_wpredictions$w_final <- (tbt_matrices_wpredictions$w +  tbt_matrices_wpredictions$w_int_rme) +
  (tbt_matrices_wpredictions$w_beta + tbt_matrices_wpredictions$w_beta_rme)

tbt_matrices_wpredictions$u_final <- (tbt_matrices_wpredictions$u +  tbt_matrices_wpredictions$u_int_rme) +
  (tbt_matrices_wpredictions$u_beta + tbt_matrices_wpredictions$u_beta_rme)

tbt_matrices_wpredictions$H_final <- (tbt_matrices_wpredictions$H +  tbt_matrices_wpredictions$H_int_rme) +
  (tbt_matrices_wpredictions$H_beta + tbt_matrices_wpredictions$H_beta_rme)

tbt_matrices_wpredictions$t_final <- exp(tbt_matrices_wpredictions$t_final)
tbt_matrices_wpredictions$w_final <- exp(tbt_matrices_wpredictions$w_final)
tbt_matrices_wpredictions$u_final <- exp(tbt_matrices_wpredictions$u_final)
tbt_matrices_wpredictions$H_final <- exp(tbt_matrices_wpredictions$H_final)
tbt_matrices_wpredictions$s_final <- tbt_matrices_wpredictions$H_final/(1+tbt_matrices_wpredictions$H_final)

tbt_matrices_wpredictions$Bn_predictions <- 0
tbt_matrices_wpredictions$Bn_predictions <- Sanabria_BHEcon(tbt_matrices_wpredictions$t_final, 
                                                            tbt_matrices_wpredictions$u_final, 
                                                            tbt_matrices_wpredictions$w_final, 
                                                            tbt_matrices_wpredictions$s_final, 
                                                            tbt_matrices_wpredictions$PR, 
                                                            tbt_matrices_wpredictions$RewMag)


```

```{r}

ggplot() + 
  geom_point(data=tbt_matrices_wpredictions, aes(x=PR,y=Local.Rate,color=as.factor(LeverHeight)),size=2) + 
  geom_line(data=tbt_matrices_wpredictions,aes(x=PR,y=Bn_predictions,color=as.factor(LeverHeight)),size=3) +
  ylab("Local Rate") + 
  xlab("Progressive Ratio")+
  facet_wrap(~reCode_Subject)

```






