---
title: "Affordances Behavioral Econ Analysis following Sanabria (in prep)"
author: "Carter Daniels"
date: "1/1/2024"
output: html_document
---

```{r, include=FALSE}
rm(list=ls())
#import libraries
library(tidyverse)
library(lme4)
library(stats)
library(shinystan)
library(cmdstanr)
library(posterior)
library(bayesplot)
library(ggridges)
library(patchwork)
library(ggtext)
library(ggprism)
library(Hmisc)

```


```{r, include=FALSE}

#datapath and functions

data.path <- "E:\\Dropbox\\2 All of Carter's Stuff\\Carter Local\\BHA_Econ_Sanabria\\"


Sanabria_BHEcon <- function(t,z,w,Qplus,PR,RM,ST) 
{
  rho <- t+(PR/(w*RM))
  demand <- Qplus*((z+t*rho)/(z+(rho^2)))
  Bn <- ((demand*PR)/(RM*ST))/60
  return(list(demand,Bn))

}
```

```{r, include=FALSE}

tbt_matrices <- read.csv(paste0(data.path,"AH_LongForm_Carter.csv"))


#recode subjects
tbt_matrices$reCode_Subject <- 1
i=0
for (subj in unique(tbt_matrices$Rat))
{
  i = i + 1
  tbt_matrices$reCode_Subject[tbt_matrices$Rat==subj]<-i
}

tbt_matrices$LeverRecode <- tbt_matrices$LeverHeight - min(tbt_matrices$LeverHeight)

tbt_matrices$RewMag <- 1

tbt_matrices$CatLH <- 0
tbt_matrices$CatLH[tbt_matrices$LeverHeight==11]<-1
tbt_matrices$CatLH[tbt_matrices$LeverHeight==18]<-2


tbt_matrices$cumTime <- ave(tbt_matrices$Time,tbt_matrices$Rat,
                                tbt_matrices$Session,tbt_matrices$LeverHeight,
                                FUN=cumsum)

#for now only include through the last non zero but not necessairily completed PR
tbt_matrices <- tbt_matrices[tbt_matrices$Completed==1,]
tbt_matrices <- tbt_matrices[tbt_matrices$Local.Rate!=0,]
tbt_matrices$SessionTime <- 30

#tbt_matrices <- tbt_matrices[tbt_matrices$LeverRecode==10,]
#tbt_matrices <- tbt_matrices[tbt_matrices$CatLH==1,]

OverSessions <- tbt_matrices %>% group_by(reCode_Subject,CatLH,PR,RewMag) %>% 
  summarise(across(.cols=c(Local.Rate),.fns=c(median,sd)))
OverSessions$Local.Rate_3 <- OverSessions$Local.Rate_2 / OverSessions$Local.Rate_1
colnames(OverSessions)[colnames(OverSessions)=="Local.Rate_1"] <- "Local.Rate"
OverSessions$SessionTime <- 30

```


# Individual Data (scatter plots)


```{r, fig.width = 24, fig.height = 24, echo=FALSE, results='hide', message=FALSE, warning=FALSE}

ggplot() + 
  geom_point(data=tbt_matrices, aes(x=PR,y=Local.Rate,color=as.factor(CatLH)),size=2) + 
  geom_line(data=OverSessions,aes(x=PR,y=Local.Rate,color=as.factor(CatLH)),size=3) +
  ylab("Local Rate") + 
  xlab("Progressive Ratio")+
  facet_wrap(~reCode_Subject)

ggplot() + 
  geom_line(data=OverSessions,aes(x=PR,y=Local.Rate_2,color=as.factor(CatLH)),size=3) +
  ylab("Standard Deviation") + 
  xlab("Progressive Ratio") + 
  facet_wrap(~reCode_Subject)

ggplot() + 
  geom_line(data=OverSessions,aes(x=PR,y=Local.Rate_3,color=as.factor(CatLH)),size=3) +
  ylab("Coefficient of Variation") + 
  xlab("Progressive Ratio") + 
  facet_wrap(~reCode_Subject)

```



```{r, include=FALSE}

sanabria_econ <- "

// stan code for sanabria behavioral econ

data {

 int<lower=1> Nr; // number of data points
 int<lower=1> Ns; // number of subjects
 vector[Nr] y; //Local Rate stream
 int s[Nr]; //subject stream
 vector<lower=0>[Nr] Pr_req; //Programemd PR stream
 vector<lower=0>[Nr] LHStream; //Lever height stream
 vector<lower=1>[Nr] RewMagStream; //Reward Magnitude Stream
 vector<lower=0>[Nr] SessionTime; //TotalSessionTime
 real minTau; //min Tau
}

parameters {

//intercept
real t_int; 
real w_int;
real z_int; 
real Qlogit_int; 
real sigma_int;

//lever height effect
real t_beta_11;
real w_beta_11;
real z_beta_11; 
real Qlogit_beta_11; 
real sigma_beta_11;

real t_beta_18;
real w_beta_18;
real z_beta_18; 
real Qlogit_beta_18; 
real sigma_beta_18;

//intercept_rme;
vector[Ns] t_int_rme; 
vector[Ns] w_int_rme;
vector[Ns] z_int_rme;
vector[Ns] Qlogit_int_rme; 
vector[Ns] sigma_int_rme;

//lever height rme;
vector[Ns] t_beta_11_rme;
vector[Ns] w_beta_11_rme;
vector[Ns] z_beta_11_rme;
vector[Ns] Qlogit_beta_11_rme; 
vector[Ns] sigma_beta_11_rme;

vector[Ns] t_beta_18_rme;
vector[Ns] w_beta_18_rme;
vector[Ns] z_beta_18_rme;
vector[Ns] Qlogit_beta_18_rme;
vector[Ns] sigma_beta_18_rme;

}

transformed parameters {

vector[Nr] row_Bn; 
vector<lower=0>[Nr] row_Qplus;
vector<lower=0>[Nr] row_upper; 
vector<lower=0>[Nr] row_rho; 
vector<lower=0>[Nr] row_demand;
vector<lower=0>[Nr] row_sigma; 
vector<lower=0>[Nr] t;
vector<lower=0>[Nr] w;
vector<lower=0>[Nr] z;
vector<lower=0,upper=1>[Nr] Qprop; 

for (si in 1:Nr)
{
  if (LHStream[si] == 0)
  {
    t[si] = exp((t_int + t_int_rme[s[si]]))+minTau;
    w[si] = exp((w_int + w_int_rme[s[si]]));
    z[si] = exp((z_int + z_int_rme[s[si]]));
    Qprop[si] = exp(Qlogit_int + Qlogit_int_rme[s[si]])/(1+exp(Qlogit_int + Qlogit_int_rme[s[si]])); 
    row_sigma[si] = exp((sigma_int + sigma_int_rme[s[si]]));

  }
  else if (LHStream[si] == 1)
  {
    t[si] = exp((t_int + t_int_rme[s[si]])+((t_beta_11 + t_beta_11_rme[s[si]])*1))+minTau;
    w[si] = exp((w_int + w_int_rme[s[si]])+((w_beta_11 + w_beta_11_rme[s[si]])*1));
    z[si] = exp((z_int + z_int_rme[s[si]])+((z_beta_11 + z_beta_11_rme[s[si]])*1));
    Qprop[si] = exp((Qlogit_int + Qlogit_int_rme[s[si]])+((Qlogit_beta_11 + Qlogit_beta_11_rme[s[si]])*1))/(1+exp((Qlogit_int + Qlogit_int_rme[s[si]])+((Qlogit_beta_11 + Qlogit_beta_11_rme[s[si]])*1)));
    row_sigma[si] = exp((sigma_int + sigma_int_rme[s[si]])+((sigma_beta_11 + sigma_beta_11_rme[s[si]])*1));


  }
  else if (LHStream[si] == 2)
  {
    t[si] = exp((t_int + t_int_rme[s[si]])+((t_beta_11 + t_beta_11_rme[s[si]])*1)+((t_beta_18 + t_beta_18_rme[s[si]])*1))+minTau;
    w[si] = exp((w_int + w_int_rme[s[si]])+((w_beta_11 + w_beta_11_rme[s[si]])*1)+((w_beta_18 + w_beta_18_rme[s[si]])*1));
    z[si] = exp((z_int + z_int_rme[s[si]])+((z_beta_11 + z_beta_11_rme[s[si]])*1)+((z_beta_18 + z_beta_18_rme[s[si]])*1));
    Qprop[si] = exp((Qlogit_int + Qlogit_int_rme[s[si]])+((Qlogit_beta_11 + Qlogit_beta_11_rme[s[si]])*1)+((Qlogit_beta_18 + Qlogit_beta_18_rme[s[si]])*1))/(1+exp((Qlogit_int + Qlogit_int_rme[s[si]])+((Qlogit_beta_11 + Qlogit_beta_11_rme[s[si]])*1)+((Qlogit_beta_18 + Qlogit_beta_18_rme[s[si]])*1)));
    row_sigma[si] = exp((sigma_int + sigma_int_rme[s[si]])+((sigma_beta_11 + sigma_beta_11_rme[s[si]])*1)+((sigma_beta_18 + sigma_beta_18_rme[s[si]])*1));

  }

  row_rho[si] = t[si]+(Pr_req[si]/(w[si]*RewMagStream[si]));
  
  row_upper[si] = (z[si]*pow(1/t[si],2)+1)/(z[si]*(1/t[si])+t[si]);
  
  row_Qplus[si] =  row_upper[si] * Qprop[si]; 
  
  row_demand[si] = row_Qplus[si]*((z[si]+t[si]*row_rho[si])/(z[si]+pow(row_rho[si],2))); 

  row_Bn[si] = ((row_demand[si]*Pr_req[si])/(RewMagStream[si]*SessionTime[si]))/60;

}



}

model {

//intercept priors
t_int ~ normal(0,10);
w_int ~ normal(0,10);
z_int ~ normal(0,10); 
Qlogit_int ~ normal(0,10);
sigma_int ~ normal(-2,0.25);

//beta priors
t_beta_11 ~ normal(0,1);
w_beta_11 ~ normal(0,1);
z_beta_11 ~ normal(0,1); 
Qlogit_beta_11 ~ normal(0,1);
sigma_beta_11 ~ normal(0,0.25);

t_beta_18 ~ normal(0,1);
w_beta_18 ~ normal(0,1);
z_beta_18 ~ normal(0,1); 
Qlogit_beta_18 ~ normal(0,1);
sigma_beta_18 ~normal(0,0.25);

//rme priors
t_int_rme ~ normal(0,1);
w_int_rme ~ normal(0,1);
z_int_rme ~ normal(0,1); 
Qlogit_int_rme ~ normal(0,1);
sigma_int_rme ~ normal(0,0.25);


t_beta_11_rme ~ normal(0,1);
w_beta_11_rme ~ normal(0,1);
z_beta_11_rme ~ normal(0,1); 
Qlogit_beta_11_rme ~ normal(0,1);
sigma_beta_11_rme ~ normal(0,0.25);

t_beta_18_rme ~ normal(0,1);
w_beta_18_rme ~ normal(0,1);
z_beta_18_rme ~ normal(0,1); 
Qlogit_beta_18_rme ~ normal(0,1);
sigma_beta_18_rme ~ normal(0,0.25);

//likelihood
y ~ normal(log(row_Bn),row_sigma); //sigma

}


"

write_stan_file(sanabria_econ,
                dir=data.path,
                basename="sanabria_econ_Angeldata_revFconstrained_Alt.stan",
                force_overwrite = TRUE)

#compile model
mod <- cmdstan_model(stan_file=file.path(paste0(data.path,
                                                "sanabria_econ_Angeldata_revFconstrained_Alt.stan")))

##got divergent transitions
## potentially try making every rme scaled as described here: 
# https://betanalpha.github.io/assets/case_studies/divergences_and_bias.html#7_original_computing_environment
# mu + tau*rme; rme ~N(0,1); tau ~ half-cauchy(0,5)
#also consider modeling covariance
#https://betanalpha.github.io/assets/case_studies/divergences_and_bias.html#3_a_non-centered_eight_schools_implementation

```

```{r, include=FALSE}
#construct predictor matrix
minTau = 0.0128

data_list <- list(Nr = nrow(tbt_matrices),
                  Ns = length(unique(tbt_matrices$reCode_Subject)),
                  y=log(tbt_matrices$Local.Rate),
                  s=tbt_matrices$reCode_Subject, 
                  Pr_req = tbt_matrices$PR,
                  LHStream = tbt_matrices$CatLH, 
                  RewMagStream = tbt_matrices$RewMag,
                  SessionTime = tbt_matrices$SessionTime,
                  minTau = minTau)




```


```{r, include=FALSE}

## mcmc

# fit <- mod$sample(data=data_list,
#                   seed=123,
#                   chains=4,
#                   parallel_chains = 4,
#                   refresh=100,
#                   num_samples=20000,
#                   num_warmup=20000,
#                   adapt_delta=0.99,
#                   max_treedepth=30,
#                   #step_size = 0.0005,
#                   output_dir="E:/Dropbox/2 All of Carter's Stuff/Carter Local/BHA_Econ_Sanabria/AngelBayesOutput")
# a <- fit$summary()

fit <- mod$optimize(data=data_list,algorithm="lbfgs",tol_obj = 1e-48,iter=20000)
a <- fit$summary()

# csvs <- list.files("E:/Dropbox/2 All of Carter's Stuff/Carter Local/BHA_Econ_Sanabria/AngelBayesOutput")
# csvs <- csvs[2:5]
# fit <- as_cmdstan_fit(paste0("E:/Dropbox/2 All of Carter's Stuff/Carter Local/BHA_Econ_Sanabria/AngelBayesOutput/",
#                              csvs), 
#                       check_diagnostics = TRUE)
# a <- fit$summary()


```

```{r}
sub_mcmc_draws <- fit$draws(variables=c("t_int","w_int","z_int","Qlogit_int"))
sub_np <- nuts_params(fit)
mcmc_pairs(sub_mcmc_draws,pars=c("t_int","w_int","z_int","Qlogit_int"),np=sub_np)
color_scheme_set("viridis")
mcmc_trace(sub_mcmc_draws,pars=c("t_int","w_int","z_int","Qlogit_int"),np=sub_np)

mcmc_draws_ <- fit$draws(variables=c("t_int","w_int","z_int","Qlogit_int","sigma_int", 
                                    "t_beta_11","w_beta_11","z_beta_11","Qlogit_beta_11",
                                    "t_beta_18","w_beta_18","z_beta_18","Qlogit_beta_18", 
                                    "sigma_beta_11", "sigma_beta_18"),
                        format="df")




```

```{r}

tbt_matrices_wpredictions <- tbt_matrices
fixed_effects <- a[c(2:16),]
rmes <- a[c(14:136),]

colnames(fixed_effects)[2]<-"mean"
colnames(rmes)[2]<-"mean"

#integer or values for LH = 0
tbt_matrices_wpredictions$t <- fixed_effects$mean[1]
tbt_matrices_wpredictions$w <- fixed_effects$mean[2]
tbt_matrices_wpredictions$z <- fixed_effects$mean[3]
tbt_matrices_wpredictions$Qlogit <- fixed_effects$mean[4]


#columns for LH = 1 and LH = 2
tbt_matrices_wpredictions$t_beta_11 <- 0
tbt_matrices_wpredictions$w_beta_11 <- 0
tbt_matrices_wpredictions$z_beta_11 <- 0
tbt_matrices_wpredictions$Qlogit_beta_11 <- 0
tbt_matrices_wpredictions$t_beta_18 <- 0
tbt_matrices_wpredictions$w_beta_18 <- 0
tbt_matrices_wpredictions$z_beta_18 <- 0
tbt_matrices_wpredictions$Qlogit_beta_18 <- 0

#fill those columns where appropriate
tbt_matrices_wpredictions$t_beta_11[tbt_matrices_wpredictions$CatLH==1] <- fixed_effects$mean[6]
tbt_matrices_wpredictions$w_beta_11[tbt_matrices_wpredictions$CatLH==1] <- fixed_effects$mean[7]
tbt_matrices_wpredictions$z_beta_11[tbt_matrices_wpredictions$CatLH==1] <- fixed_effects$mean[8]
tbt_matrices_wpredictions$Qlogit_beta_11[tbt_matrices_wpredictions$CatLH==1] <- fixed_effects$mean[9]
tbt_matrices_wpredictions$t_beta_18[tbt_matrices_wpredictions$CatLH==2] <- fixed_effects$mean[6] + fixed_effects$mean[11]
tbt_matrices_wpredictions$w_beta_18[tbt_matrices_wpredictions$CatLH==2] <- fixed_effects$mean[7] + fixed_effects$mean[12]
tbt_matrices_wpredictions$z_beta_18[tbt_matrices_wpredictions$CatLH==2] <- fixed_effects$mean[8] + fixed_effects$mean[13]
tbt_matrices_wpredictions$Qlogit_beta_18[tbt_matrices_wpredictions$CatLH==2] <- fixed_effects$mean[9] + fixed_effects$mean[14]

tbt_matrices_wpredictions$t_int_rme <- 0
tbt_matrices_wpredictions$w_int_rme <- 0
tbt_matrices_wpredictions$z_int_rme <- 0
tbt_matrices_wpredictions$Qlogit_int_rme <- 0

tbt_matrices_wpredictions$t_beta_11_rme <- 0
tbt_matrices_wpredictions$w_beta_11_rme <- 0
tbt_matrices_wpredictions$z_beta_11_rme <- 0
tbt_matrices_wpredictions$Qlogit_beta_11_rme <- 0

tbt_matrices_wpredictions$t_beta_18_rme <- 0
tbt_matrices_wpredictions$w_beta_18_rme <- 0
tbt_matrices_wpredictions$z_beta_18_rme <- 0
tbt_matrices_wpredictions$Qlogit_beta_18_rme <- 0

for (ea_subj in unique(tbt_matrices_wpredictions$reCode_Subject))
{
  tbt_matrices_wpredictions$t_int_rme[which(tbt_matrices_wpredictions$reCode_Subject==ea_subj)] <- rmes$mean[which(grepl(as.character(ea_subj),rmes$variable) & 
                                                                                                                     grepl("t_int_rme",rmes$variable) & 
                                                                                                                     !grepl("Qlogit_int_rme",rmes$variable))]
  
  tbt_matrices_wpredictions$w_int_rme[tbt_matrices_wpredictions$reCode_Subject==ea_subj] <- rmes$mean[which(grepl(as.character(ea_subj),rmes$variable) &
                                                           grepl("w_int_rme",rmes$variable))]
  tbt_matrices_wpredictions$z_int_rme[tbt_matrices_wpredictions$reCode_Subject==ea_subj] <- rmes$mean[which(grepl(as.character(ea_subj),rmes$variable) &
                                                           grepl("z_int_rme",rmes$variable))]
   tbt_matrices_wpredictions$Qlogit_int_rme[tbt_matrices_wpredictions$reCode_Subject==ea_subj] <- rmes$mean[which(grepl(as.character(ea_subj),rmes$variable) &
                                                            grepl("Qlogit_int_rme",rmes$variable))]

  tbt_matrices_wpredictions$t_beta_11_rme[which(tbt_matrices_wpredictions$reCode_Subject==ea_subj &
                                                   tbt_matrices_wpredictions$CatLH==1)] <-
     rmes$mean[which(grepl("t_beta_11_rme",rmes$variable) 
                     & !grepl("Qlogit_beta_11_rme",rmes$variable))][ea_subj]
  
   tbt_matrices_wpredictions$w_beta_11_rme[which(tbt_matrices_wpredictions$reCode_Subject==ea_subj &
                                                   tbt_matrices_wpredictions$CatLH==1)] <-
     rmes$mean[which(grepl("w_beta_11_rme",rmes$variable))][ea_subj]
  
   tbt_matrices_wpredictions$z_beta_11_rme[which(tbt_matrices_wpredictions$reCode_Subject==ea_subj &
                                                   tbt_matrices_wpredictions$CatLH==1)] <-
     rmes$mean[which(grepl("z_beta_11_rme",rmes$variable))][ea_subj]

   tbt_matrices_wpredictions$Qlogit_beta_11_rme[which(tbt_matrices_wpredictions$reCode_Subject==ea_subj &
                                                   tbt_matrices_wpredictions$CatLH==1)] <-
     rmes$mean[which(grepl("Qlogit_beta_11_rme",rmes$variable))][ea_subj]
  
  
   tbt_matrices_wpredictions$t_beta_18_rme[which(tbt_matrices_wpredictions$reCode_Subject==ea_subj &
                                                   tbt_matrices_wpredictions$CatLH==2)] <- rmes$mean[which(grepl("t_beta_11_rme",rmes$variable) 
                     & !grepl("Qlogit_beta_11_rme",rmes$variable))][ea_subj] + 
     rmes$mean[which(grepl("t_beta_18_rme",rmes$variable) & 
                       !grepl("Qlogit_beta_18_rme",rmes$variable))][ea_subj]
   
   tbt_matrices_wpredictions$w_beta_18_rme[which(tbt_matrices_wpredictions$reCode_Subject==ea_subj & 
                                                   tbt_matrices_wpredictions$CatLH==2)] <- rmes$mean[which(grepl("w_beta_11_rme",rmes$variable))][ea_subj] + 
     rmes$mean[which(grepl("w_beta_18_rme",rmes$variable))][ea_subj]
   
   tbt_matrices_wpredictions$z_beta_18_rme[which(tbt_matrices_wpredictions$reCode_Subject==ea_subj &
                                                   tbt_matrices_wpredictions$CatLH==2)] <- rmes$mean[which(grepl("z_beta_11_rme",rmes$variable))][ea_subj] + 
     rmes$mean[which(grepl("z_beta_18_rme",rmes$variable))][ea_subj]
  
   tbt_matrices_wpredictions$Qlogit_beta_18_rme[which(tbt_matrices_wpredictions$reCode_Subject==ea_subj & 
                                                   tbt_matrices_wpredictions$CatLH==2)] <-
     rmes$mean[which(grepl("Qlogit_beta_18_rme",rmes$variable))][ea_subj] + rmes$mean[which(grepl("Qlogit_beta_11_rme",rmes$variable))][ea_subj]
}

tbt_matrices_wpredictions$t_final <- (tbt_matrices_wpredictions$t +  tbt_matrices_wpredictions$t_int_rme) +
  (tbt_matrices_wpredictions$t_beta_11 + tbt_matrices_wpredictions$t_beta_11_rme) + 
  (tbt_matrices_wpredictions$t_beta_18 + tbt_matrices_wpredictions$t_beta_11_rme) 

tbt_matrices_wpredictions$w_final <- (tbt_matrices_wpredictions$w +  tbt_matrices_wpredictions$w_int_rme) +
  (tbt_matrices_wpredictions$w_beta_11 + tbt_matrices_wpredictions$w_beta_11_rme) + 
  (tbt_matrices_wpredictions$w_beta_18 + tbt_matrices_wpredictions$w_beta_18_rme)

tbt_matrices_wpredictions$z_final <- (tbt_matrices_wpredictions$z +  tbt_matrices_wpredictions$z_int_rme) +
  (tbt_matrices_wpredictions$z_beta_11 + tbt_matrices_wpredictions$z_beta_11_rme) + 
  (tbt_matrices_wpredictions$z_beta_18 + tbt_matrices_wpredictions$z_beta_18_rme)

tbt_matrices_wpredictions$Qplus_final <- (tbt_matrices_wpredictions$Qlogit +  tbt_matrices_wpredictions$Qlogit_int_rme) +
  (tbt_matrices_wpredictions$Qlogit_beta_11 + tbt_matrices_wpredictions$Qlogit_beta_11_rme) + 
  (tbt_matrices_wpredictions$Qlogit_beta_18 + tbt_matrices_wpredictions$Qlogit_beta_18_rme)

tbt_matrices_wpredictions$t_final <- exp(tbt_matrices_wpredictions$t_final)+minTau
tbt_matrices_wpredictions$w_final <- exp(tbt_matrices_wpredictions$w_final)
tbt_matrices_wpredictions$z_final <- exp(tbt_matrices_wpredictions$z_final)
tbt_matrices_wpredictions$Qlogit_final <- exp(tbt_matrices_wpredictions$Qplus_final)/(exp(tbt_matrices_wpredictions$Qplus_final)+1)


tbt_matrices_wpredictions$upper <- (tbt_matrices_wpredictions$z_final*((1/tbt_matrices_wpredictions$t_final)^2)+1)/(tbt_matrices_wpredictions$z_final*(1/tbt_matrices_wpredictions$t_final)+tbt_matrices_wpredictions$t_final)
  
  
tbt_matrices_wpredictions$Qplus_final <- tbt_matrices_wpredictions$upper*tbt_matrices_wpredictions$Qlogit_final
#tbt_matrices_wpredictions$Qplus_final <- 1500*tbt_matrices_wpredictions$Qlogit_final


tbt_matrices_wpredictions$Demand_predictions <- 0
tbt_matrices_wpredictions$Bn_predictions <- 0

tbt_matrices_wpredictions$Demand_predictions <- Sanabria_BHEcon(tbt_matrices_wpredictions$t_final,
                                                            tbt_matrices_wpredictions$z_final,
                                                            tbt_matrices_wpredictions$w_final,
                                                            tbt_matrices_wpredictions$Qplus_final,
                                                            tbt_matrices_wpredictions$PR,
                                                            tbt_matrices_wpredictions$RewMag,
                                                            tbt_matrices_wpredictions$SessionTime)[[1]]

tbt_matrices_wpredictions$Bn_predictions <- Sanabria_BHEcon(tbt_matrices_wpredictions$t_final,
                                                            tbt_matrices_wpredictions$z_final,
                                                            tbt_matrices_wpredictions$w_final,
                                                            tbt_matrices_wpredictions$Qplus_final,
                                                            tbt_matrices_wpredictions$PR,
                                                            tbt_matrices_wpredictions$RewMag,
                                                            tbt_matrices_wpredictions$SessionTime)[[2]]




```

```{r}

#mean estimates for each subject
mean_persubject_persession <- tbt_matrices_wpredictions %>% group_by(Rat,LeverHeight) %>%
  summarise(across(.cols=c(t_final:Qplus_final),.fns=c(mean))) %>% pivot_longer(cols=c(t_final_1:Qplus_final_1))

ggplot() + 
  geom_boxplot(data=mean_persubject_persession,aes(x=as.factor(LeverHeight),y=log(value))) + 
  geom_point(data=mean_persubject_persession,aes(x=as.factor(LeverHeight),y=log(value))) + 
  geom_line(data=mean_persubject_persession,aes(x=as.factor(LeverHeight),y=log(value),group=Rat)) + 
  facet_wrap(~name, scales="free")

```

```{r}

ggplot() + 
  geom_line(data=tbt_matrices_wpredictions,aes(x=PR,y=Demand_predictions,color=as.factor(CatLH)),size=3) +
  ylab("Demand") + 
  xlab("Progressive Ratio")+
  facet_wrap(~reCode_Subject)

ggplot() + 
  geom_point(data=tbt_matrices_wpredictions, aes(x=PR,y=log(Local.Rate),color=as.factor(CatLH)),size=2) + 
  geom_line(data=OverSessions,aes(x=PR,y=log(Local.Rate),color=as.factor(CatLH)),size=1) +
  geom_line(data=tbt_matrices_wpredictions,aes(x=PR,y=log(Bn_predictions),color=as.factor(CatLH)),size=3) +
  ylab("Local Rate") + 
  xlab("Progressive Ratio")+
  facet_wrap(~reCode_Subject)

ggsave(paste0(data.path,paste0("tau_min_",as.character(minTau),"_model_log_test.png")), dpi = 1200, width = 12, height = 9, units = "in")


ggplot() + 
  geom_point(data=tbt_matrices_wpredictions, aes(x=PR,y=Local.Rate,color=as.factor(CatLH)),size=2) + 
  geom_line(data=OverSessions,aes(x=PR,y=Local.Rate,color=as.factor(CatLH)),size=1) +
  geom_line(data=tbt_matrices_wpredictions,aes(x=PR,y=Bn_predictions,color=as.factor(CatLH)),size=3) +
  ylab("Local Rate") + 
  xlab("Progressive Ratio")+
  facet_wrap(~reCode_Subject)

ggsave(paste0(data.path,paste0("tau_min_",as.character(minTau),"_model_ns_test.png")), dpi = 1200, width = 12, height = 9, units = "in")


```






